### ISSUE TITLE
Fix titles

### ISSUE THREAD

**Issue by rodrigosiqueira** [webfolder/siqueira.tech#11]
If we `###` the size is huge, see

![improve_titles](https://user-images.githubusercontent.com/3153524/67610585-e9eca800-f761-11e9-8b92-e3f28e51c33b.png)

**Comment by aquilamacedo** [comment]
I can't reproduce this error from my side, as the problem has already been resolved when handling titles and subtitles.

![first_image](https://user-images.githubusercontent.com/43859386/151108925-3fa5b350-6981-470e-bf9d-49c0c3b77f8f.png)
![second_image](https://user-images.githubusercontent.com/43859386/151108935-85c6a6aa-f561-434e-b2f0-979ea8bb4560.png)

**Comment by rodrigosiqueira** [comment]
Thanks
