### ISSUE TITLE
Control youtube video size

### ISSUE THREAD

**Issue by rodrigosiqueira** [webfolder/siqueira.tech#14]
We don't have a control of the youtube size, see:

![control_video_size](https://user-images.githubusercontent.com/3153524/67610679-58ca0100-f762-11e9-9106-bc3dfa20be61.png)

**Comment by aquilamacedo** [comment]
I was trying to reproduce the error and apparently, the implementation of content delimitation has already solved this problem.

![control_youtube](https://user-images.githubusercontent.com/43859386/151107759-e8a8c17f-4b9a-4b0e-9221-efe9e77ca7a6.png)

**Comment by rodrigosiqueira** [comment]
Thanks
